apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: k8s-basics
  labels:
    app: laravel-nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"        # порт твоего контейнера (или сервиса)
    prometheus.io/path: "/metrics"  # маршрут Laravel
spec:
  selector:
    app: laravel-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80