apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-metrics
  namespace: k8s-basics
  labels:
    app.kubernetes.io/name: gateway-ingress
    app.kubernetes.io/component: controller
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"     # порт метрик nginx-ingress
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: gateway-ingress
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: 10254
      targetPort: 10254